window.TRIVIA_BANK = [
  /* =========================
     Science (S001–S060) — unchanged
  ========================= */
  {id:"S001",cat:"Science",q:"What is the chemical symbol for gold?",a:"Au"},
  {id:"S002",cat:"Science",q:"What gas do plants absorb from the atmosphere for photosynthesis?",a:"carbon dioxide",alts:["co2"]},
  {id:"S003",cat:"Science",q:"What is the powerhouse of the cell?",a:"mitochondria",alts:["mitochondrion"]},
  {id:"S004",cat:"Science",q:"What is Earth's largest ocean?",a:"pacific ocean",alts:["pacific"]},
  {id:"S005",cat:"Science",q:"What particle has a negative electric charge?",a:"electron"},
  {id:"S006",cat:"Science",q:"What is the most abundant gas in Earth's atmosphere?",a:"nitrogen"},
  {id:"S007",cat:"Science",q:"What is the boiling point of water in Celsius at sea level?",a:"100",alts:["100°C","100 c"]},
  {id:"S008",cat:"Science",q:"What organ pumps blood through the body?",a:"heart"},
  {id:"S009",cat:"Science",q:"What is the chemical formula for water?",a:"h2o"},
  {id:"S010",cat:"Science",q:"What is the nearest star to Earth?",a:"the sun",alts:["sun"]},
  {id:"S011",cat:"Science",q:"What force keeps planets in orbit?",a:"gravity"},
  {id:"S012",cat:"Science",q:"What is the hardest natural substance?",a:"diamond"},
  {id:"S013",cat:"Science",q:"What is the unit of electrical resistance?",a:"ohm",alts:["Ω"]},
  {id:"S014",cat:"Science",q:"What is the pH of a neutral solution at 25°C?",a:"7"},
  {id:"S015",cat:"Science",q:"What blood type is known as the universal donor (red cells)?",a:"o negative",alts:["o-","o minus"]},
  {id:"S016",cat:"Science",q:"What vitamin is produced when skin is exposed to sunlight?",a:"vitamin d",alts:["d"]},
  {id:"S017",cat:"Science",q:"What is the largest planet in our solar system?",a:"jupiter"},
  {id:"S018",cat:"Science",q:"What gas is most associated with the greenhouse effect from fossil fuel burning?",a:"carbon dioxide",alts:["co2"]},
  {id:"S019",cat:"Science",q:"What is the main component of natural gas?",a:"methane"},
  {id:"S020",cat:"Science",q:"What do we call animals that eat both plants and meat?",a:"omnivores",alts:["omnivore"]},
  {id:"S021",cat:"Science",q:"What is the name of the process by which liquid water becomes vapor?",a:"evaporation"},
  {id:"S022",cat:"Science",q:"What is the largest organ in the human body?",a:"skin"},
  {id:"S023",cat:"Science",q:"What is the basic unit of life?",a:"cell"},
  {id:"S024",cat:"Science",q:"What do we call the study of weather?",a:"meteorology"},
  {id:"S025",cat:"Science",q:"What is the chemical symbol for sodium?",a:"na"},
  {id:"S026",cat:"Science",q:"What is the chemical symbol for iron?",a:"fe"},
  {id:"S027",cat:"Science",q:"What is the speed of light in vacuum (approx., km/s)?",a:"300000",alts:["299792","299792 km/s"]},
  {id:"S028",cat:"Science",q:"What part of the brain controls balance and coordination?",a:"cerebellum"},
  {id:"S029",cat:"Science",q:"What is the name of the galaxy that contains our solar system?",a:"milky way",alts:["milky way galaxy"]},
  {id:"S030",cat:"Science",q:"What is the common name for sodium chloride?",a:"salt",alts:["table salt"]},
  {id:"S031",cat:"Science",q:"What is the smallest unit of an element that retains its properties?",a:"atom"},
  {id:"S032",cat:"Science",q:"What is the planet known as the Red Planet?",a:"mars"},
  {id:"S033",cat:"Science",q:"What do you call a scientist who studies rocks and Earth's structure?",a:"geologist"},
  {id:"S034",cat:"Science",q:"What is the primary gas in the Sun?",a:"hydrogen"},
  {id:"S035",cat:"Science",q:"What is the name of the pigment that makes plants green?",a:"chlorophyll"},
  {id:"S036",cat:"Science",q:"What is the most common element in Earth's crust?",a:"oxygen"},
  {id:"S037",cat:"Science",q:"What is the name of the organ that filters blood and produces urine?",a:"kidney",alts:["kidneys"]},
  {id:"S038",cat:"Science",q:"What is the SI unit of force?",a:"newton",alts:["n"]},
  {id:"S039",cat:"Science",q:"What is the SI unit of energy?",a:"joule",alts:["j"]},
  {id:"S040",cat:"Science",q:"What do bees collect and use to make honey?",a:"nectar"},
  {id:"S041",cat:"Science",q:"What is the name for molten rock beneath Earth's surface?",a:"magma"},
  {id:"S042",cat:"Science",q:"What is the name for molten rock after it erupts onto the surface?",a:"lava"},
  {id:"S043",cat:"Science",q:"What is the primary function of red blood cells?",a:"carry oxygen",alts:["transport oxygen","carry oxygen to tissues"]},
  {id:"S044",cat:"Science",q:"What is the longest bone in the human body?",a:"femur"},
  {id:"S045",cat:"Science",q:"What is the name of the layer of gases surrounding Earth?",a:"atmosphere"},
  {id:"S046",cat:"Science",q:"What is the planet famous for its rings?",a:"saturn"},
  {id:"S047",cat:"Science",q:"What is the term for animals active at night?",a:"nocturnal"},
  {id:"S048",cat:"Science",q:"What do we call the process of a solid turning directly into a gas?",a:"sublimation"},
  {id:"S049",cat:"Science",q:"What is the name of the energy stored in chemical bonds?",a:"chemical energy"},
  {id:"S050",cat:"Science",q:"What is the study of heredity called?",a:"genetics"},
  {id:"S051",cat:"Science",q:"What are the tiny vessels where exchange of gases occurs in the lungs?",a:"alveoli",alts:["alveolus"]},
  {id:"S052",cat:"Science",q:"What is the name of Earth's natural satellite?",a:"moon",alts:["the moon"]},
  {id:"S053",cat:"Science",q:"What is the main organ of the nervous system?",a:"brain"},
  {id:"S054",cat:"Science",q:"What is the scientific name for humans?",a:"homo sapiens"},
  {id:"S055",cat:"Science",q:"What is the term for an animal that eats only plants?",a:"herbivore",alts:["herbivores"]},
  {id:"S056",cat:"Science",q:"What is the term for an animal that eats only meat?",a:"carnivore",alts:["carnivores"]},
  {id:"S057",cat:"Science",q:"What is the name of the instrument used to measure temperature?",a:"thermometer"},
  {id:"S058",cat:"Science",q:"Which planet is closest to the Sun?",a:"mercury"},
  {id:"S059",cat:"Science",q:"What is the term for a change in DNA sequence?",a:"mutation",alts:["a mutation"]},
  {id:"S060",cat:"Science",q:"What is the name of the process by which plants make food using sunlight?",a:"photosynthesis"},

/* =========================
   Math (M061–M110) — HARDER (BUT DOABLE IN HEAD)
========================= */
{id:"M061",cat:"Math",q:"Compute gcd(84, 126).",a:"42"},
{id:"M062",cat:"Math",q:"Compute lcm(12, 18).",a:"36"},
{id:"M063",cat:"Math",q:"What is the remainder when 7^50 is divided by 5?",a:"4"},
{id:"M064",cat:"Math",q:"How many trailing zeros does 30! have?",a:"7"},
{id:"M065",cat:"Math",q:"Simplify: 45/60.",a:"3/4",alts:["0.75"]},
{id:"M066",cat:"Math",q:"Solve: 3x − 7 = 20.",a:"9"},
{id:"M067",cat:"Math",q:"Compute: 1+2+3+…+50.",a:"1275"},
{id:"M068",cat:"Math",q:"Compute: 2+4+6+…+20.",a:"110"},
{id:"M069",cat:"Math",q:"How many distinct permutations does the word LEVEL have?",a:"30"},
{id:"M070",cat:"Math",q:"Compute: C(8,2).",a:"28"},
{id:"M071",cat:"Math",q:"Two fair dice are rolled. What is P(sum is 7)?",a:"1/6",alts:["0.1666667","0.1667"]},
{id:"M072",cat:"Math",q:"Solve: x^2 − 9 = 0. Give the larger root.",a:"3"},
{id:"M073",cat:"Math",q:"What is the determinant of [[3,2],[7,5]]?",a:"1"},
{id:"M074",cat:"Math",q:"What is the last digit of 7^2024?",a:"1"},
{id:"M075",cat:"Math",q:"Write 45% as a simplified fraction.",a:"9/20",alts:["0.45"]},
{id:"M076",cat:"Math",q:"How many diagonals does a 15-gon have?",a:"90"},
{id:"M077",cat:"Math",q:"Prime factorization: 360 =",a:"2^3*3^2*5",alts:["2^3 × 3^2 × 5","2^3x3^2x5","2*2*2*3*3*5"]},
{id:"M078",cat:"Math",q:"What is the smallest prime factor of 221?",a:"13"},
{id:"M079",cat:"Math",q:"Compute: 12345 mod 9.",a:"6"},
{id:"M080",cat:"Math",q:"If x+y=12 and x−y=4, what is x?",a:"8"},
{id:"M081",cat:"Math",q:"What is the median of 3, 7, 8, 10, 14, 18?",a:"9"},
{id:"M082",cat:"Math",q:"Solve: 5/8 = x/40.",a:"25"},
{id:"M083",cat:"Math",q:"Convert 0.125 to a simplified fraction.",a:"1/8"},
{id:"M084",cat:"Math",q:"Compute: 2^10 × 2^3.",a:"8192"},
{id:"M085",cat:"Math",q:"Compute: 9! / 7!.",a:"72"},
{id:"M086",cat:"Math",q:"How many multiples of 4 are in 1 to 100 (inclusive)?",a:"25"},
{id:"M087",cat:"Math",q:"How many positive divisors does 72 have?",a:"12"},
{id:"M088",cat:"Math",q:"If 2x+3y=19 and y=3, what is x?",a:"5"},
{id:"M089",cat:"Math",q:"A fair coin is flipped 4 times. What is P(exactly 2 heads)?",a:"3/8",alts:["0.375"]},
{id:"M090",cat:"Math",q:"Compute: 1/2 + 1/3.",a:"5/6",alts:["0.8333333","0.8333"]},
{id:"M091",cat:"Math",q:"Compute: 3.6 ÷ 0.12.",a:"30"},
{id:"M092",cat:"Math",q:"Compute: √225.",a:"15"},
{id:"M093",cat:"Math",q:"Solve: 4^x = 64.",a:"3"},
{id:"M094",cat:"Math",q:"Compute: log10(0.01).",a:"-2"},
{id:"M095",cat:"Math",q:"Arithmetic sequence: a1=5, d=3. What is a10?",a:"32"},
{id:"M096",cat:"Math",q:"Geometric sequence: 3, 6, 12, ... What is the 6th term?",a:"96"},
{id:"M097",cat:"Math",q:"Solve: |x−5|=3. One solution is 8. What is the other?",a:"2"},
{id:"M098",cat:"Math",q:"Area of a circle with radius 7 (in terms of π) =",a:"49π",alts:["49 pi","49*pi"]},
{id:"M099",cat:"Math",q:"Sum of interior angles of an 11-gon (degrees) =",a:"1620"},
{id:"M100",cat:"Math",q:"In base-10, what is binary 101101?",a:"45"},
{id:"M101",cat:"Math",q:"What is the remainder when 5^123 is divided by 4?",a:"1"},
{id:"M102",cat:"Math",q:"Compute: 13 mod 6.",a:"1"},
{id:"M103",cat:"Math",q:"Solve: x/3 + x/4 = 14.",a:"24"},
{id:"M104",cat:"Math",q:"Simplify the ratio 150:210.",a:"5:7",alts:["5 to 7"]},
{id:"M105",cat:"Math",q:"Find the mean of 6, 8, 10, 12.",a:"9"},
{id:"M106",cat:"Math",q:"A random integer from 1–20 is chosen. What is P(it is prime)?",a:"2/5",alts:["0.4"]},
{id:"M107",cat:"Math",q:"Compute: 2^5 − 3^3.",a:"5"},
{id:"M108",cat:"Math",q:"Solve: x^2 + 5x + 6 = 0. Give the larger root.",a:"-2"},
{id:"M109",cat:"Math",q:"Compute: 1+2+4+…+512.",a:"1023"},
{id:"M110",cat:"Math",q:"If 30% of x is 45, what is x?",a:"150"},

  /* =========================
     Harry Potter (HP111–HP150) — HARDER
  ========================= */
  {id:"HP111",cat:"Harry Potter",q:"What is the incantation used to conjure the Dark Mark?",a:"morsmordre"},
  {id:"HP112",cat:"Harry Potter",q:"What is the potion used to force truthful answers called?",a:"veritaserum"},
  {id:"HP113",cat:"Harry Potter",q:"What is the spell used to summon objects?",a:"accio"},
  {id:"HP114",cat:"Harry Potter",q:"What is the name of Voldemort’s snake?",a:"nagini"},
  {id:"HP115",cat:"Harry Potter",q:"What is the name of the Horcrux in Harry Potter and the Chamber of Secrets?",a:"tom riddle's diary",alts:["riddle's diary","tom riddles diary"]},
  {id:"HP116",cat:"Harry Potter",q:"Who destroyed Ravenclaw’s diadem Horcrux in the books?",a:"vincent crabbe",alts:["crabbe"]},
  {id:"HP117",cat:"Harry Potter",q:"What creature does a Basilisk fear?",a:"rooster",alts:["a rooster"]},
  {id:"HP118",cat:"Harry Potter",q:"What is the name of the goblin who helps Harry break into Gringotts?",a:"griphook"},
  {id:"HP119",cat:"Harry Potter",q:"What is the name of the spell that repairs broken objects?",a:"reparo"},
  {id:"HP120",cat:"Harry Potter",q:"What is the name of the prison guarded by Dementors?",a:"azkaban"},
  {id:"HP121",cat:"Harry Potter",q:"Who kills Dumbledore?",a:"severus snape",alts:["snape"]},
  {id:"HP122",cat:"Harry Potter",q:"What is the name of the ghost of Slytherin House?",a:"bloody baron",alts:["the bloody baron"]},
  {id:"HP123",cat:"Harry Potter",q:"What is the name of Hermione’s parents’ profession (both)?",a:"dentists",alts:["dentist"]},
  {id:"HP124",cat:"Harry Potter",q:"What is the name of the spell that produces a Patronus?",a:"expecto patronum",alts:["patronus charm"]},
  {id:"HP125",cat:"Harry Potter",q:"What is the name of the spell used to erase memories?",a:"obliviate"},
  {id:"HP126",cat:"Harry Potter",q:"What is the name of the magical contract that binds participants in the Triwizard Tournament?",a:"goblet of fire",alts:["the goblet of fire"]},
  {id:"HP127",cat:"Harry Potter",q:"Who founded Hufflepuff House?",a:"helga hufflepuff",alts:["helga"]},
  {id:"HP128",cat:"Harry Potter",q:"Who founded Ravenclaw House?",a:"rowena ravenclaw",alts:["rowena"]},
  {id:"HP129",cat:"Harry Potter",q:"Who founded Slytherin House?",a:"salazar slytherin",alts:["salazar"]},
  {id:"HP130",cat:"Harry Potter",q:"Who founded Gryffindor House?",a:"godric gryffindor",alts:["godric"]},
  {id:"HP131",cat:"Harry Potter",q:"What is the name of the tree that attacks students near Hogwarts?",a:"whomping willow",alts:["the whomping willow"]},
  {id:"HP132",cat:"Harry Potter",q:"What object must be destroyed to kill a Basilisk in the Chamber (used in the book)?",a:"sword of gryffindor",alts:["gryffindor's sword"]},
  {id:"HP133",cat:"Harry Potter",q:"What is the name of the map that shows everyone inside Hogwarts?",a:"marauder's map",alts:["marauders map","the marauder's map"]},
  {id:"HP134",cat:"Harry Potter",q:"What is the name of the room that appears when someone needs it?",a:"room of requirement",alts:["the room of requirement"]},
  {id:"HP135",cat:"Harry Potter",q:"What is the name of the Death Eater who impersonates Moody?",a:"barty crouch jr",alts:["barty crouch jr.","barty crouch junior"]},
  {id:"HP136",cat:"Harry Potter",q:"What is the name of the wand core in Harry’s wand?",a:"phoenix feather",alts:["a phoenix feather"]},
  {id:"HP137",cat:"Harry Potter",q:"What is the name of the spell used to create a silver shield/reflect spells (advanced)?",a:"protego"},
  {id:"HP138",cat:"Harry Potter",q:"What is the name of the creature that is born from a chicken egg hatched under a toad?",a:"basilisk"},
  {id:"HP139",cat:"Harry Potter",q:"What is the name of the book that Tom Riddle used to communicate with Ginny?",a:"tom riddle's diary",alts:["riddle's diary"]},
  {id:"HP140",cat:"Harry Potter",q:"What is the name of the village where Hogwarts students can visit on weekends?",a:"hogsmeade"},
  {id:"HP141",cat:"Harry Potter",q:"What is the name of the spell that opens locks?",a:"alohomora"},
  {id:"HP142",cat:"Harry Potter",q:"What is the name of the potion that allows someone to take another’s form?",a:"polyjuice potion",alts:["polyjuice"]},
  {id:"HP143",cat:"Harry Potter",q:"What is the name of the Order headquarters at number 12?",a:"grimmauld place",alts:["12 grimmauld place"]},
  {id:"HP144",cat:"Harry Potter",q:"What is the name of the centaur who teaches Divination?",a:"firenze"},
  {id:"HP145",cat:"Harry Potter",q:"What is the name of the curse that inflicts torture?",a:"cruciatus curse",alts:["crucio"]},
  {id:"HP146",cat:"Harry Potter",q:"What is the name of the curse that controls someone’s actions?",a:"imperius curse",alts:["imperio"]},
  {id:"HP147",cat:"Harry Potter",q:"What is the name of the locket Horcrux’s original owner?",a:"salazar slytherin",alts:["slytherin"]},
  {id:"HP148",cat:"Harry Potter",q:"What is the name of the spell that makes objects fly/levitate (basic)?",a:"wingardium leviosa",alts:["wingardium leviosa"]},
  {id:"HP149",cat:"Harry Potter",q:"What is the name of Harry’s Patronus?",a:"stag",alts:["a stag"]},
  {id:"HP150",cat:"Harry Potter",q:"What is the name of the magical device that stores memories as liquid?",a:"pensieve",alts:["pensive"]},

  /* =========================
     General (G151–G200) — unchanged
  ========================= */
  {id:"G151",cat:"General",q:"What is the capital of France?",a:"paris"},
  {id:"G152",cat:"General",q:"Which planet is known for its Great Red Spot?",a:"jupiter"},
  {id:"G153",cat:"General",q:"Who wrote 'Romeo and Juliet'?",a:"william shakespeare",alts:["shakespeare"]},
  {id:"G154",cat:"General",q:"In which city is the Statue of Liberty located?",a:"new york",alts:["new york city","nyc"]},
  {id:"G155",cat:"General",q:"What is the largest mammal?",a:"blue whale"},
  {id:"G156",cat:"General",q:"What is the currency of Japan?",a:"yen"},
  {id:"G157",cat:"General",q:"What is the capital of Italy?",a:"rome"},
  {id:"G158",cat:"General",q:"Which continent is the Sahara Desert on?",a:"africa"},
  {id:"G159",cat:"General",q:"What is the tallest mountain in the world (above sea level)?",a:"mount everest",alts:["everest"]},
  {id:"G160",cat:"General",q:"What is the longest river in the world?",a:"nile",alts:["the nile"]},
  {id:"G161",cat:"General",q:"What is the name of the painting with a woman smiling by Leonardo da Vinci?",a:"mona lisa"},
  {id:"G162",cat:"General",q:"Which musical instrument has 88 keys (standard)?",a:"piano"},
  {id:"G163",cat:"General",q:"What is the largest continent by area?",a:"asia"},
  {id:"G164",cat:"General",q:"What is the smallest prime number?",a:"2"},
  {id:"G165",cat:"General",q:"What is the chemical symbol for oxygen?",a:"o"},
  {id:"G166",cat:"General",q:"Which country gifted the Statue of Liberty to the United States?",a:"france"},
  {id:"G167",cat:"General",q:"What is the name of the fictional city where Batman operates?",a:"gotham",alts:["gotham city"]},
  {id:"G168",cat:"General",q:"What is the name of the Greek god of the sea?",a:"poseidon"},
  {id:"G169",cat:"General",q:"What is the largest planet in our solar system?",a:"jupiter"},
  {id:"G170",cat:"General",q:"What is the primary language spoken in Brazil?",a:"portuguese"},
  {id:"G171",cat:"General",q:"What is the term for a word that is the same forwards and backwards?",a:"palindrome"},
  {id:"G172",cat:"General",q:"What is the name of the ship on which the Pilgrims traveled to America in 1620?",a:"mayflower"},
  {id:"G173",cat:"General",q:"Which ocean is off the California coast?",a:"pacific ocean",alts:["pacific"]},
  {id:"G174",cat:"General",q:"What is the largest internal organ in the human body?",a:"liver"},
  {id:"G175",cat:"General",q:"How many players are on a soccer team on the field (per side)?",a:"11"},
  {id:"G176",cat:"General",q:"What is the main character’s name in 'The Legend of Zelda' series?",a:"link"},
  {id:"G177",cat:"General",q:"What is the capital of Canada?",a:"ottawa"},
  {id:"G178",cat:"General",q:"What instrument measures atmospheric pressure?",a:"barometer"},
  {id:"G179",cat:"General",q:"Who painted the ceiling of the Sistine Chapel (commonly credited)?",a:"michelangelo"},
  {id:"G180",cat:"General",q:"What is the name of the fictional wizard in 'The Lord of the Rings' who leads the Fellowship?",a:"gandalf"},
  {id:"G181",cat:"General",q:"What is the largest country by area?",a:"russia"},
  {id:"G182",cat:"General",q:"What is the name of the longest-running animated TV series in the US?",a:"the simpsons",alts:["simpsons"]},
  {id:"G183",cat:"General",q:"What is the capital of Australia?",a:"canberra"},
  {id:"G184",cat:"General",q:"Which element has the atomic number 1?",a:"hydrogen"},
  {id:"G185",cat:"General",q:"What is the name of the famous clock tower in London (nickname)?",a:"big ben"},
  {id:"G186",cat:"General",q:"What is the largest bone in the human body?",a:"femur"},
  {id:"G187",cat:"General",q:"Which planet is famous for its rings?",a:"saturn"},
  {id:"G188",cat:"General",q:"What is the main ingredient in guacamole?",a:"avocado",alts:["avocados"]},
  {id:"G189",cat:"General",q:"What is the name of Sherlock Holmes’s friend and assistant?",a:"dr watson",alts:["watson","john watson","dr. watson"]},
  {id:"G190",cat:"General",q:"What is the term for an angle greater than 90 degrees but less than 180 degrees?",a:"obtuse"},
  {id:"G191",cat:"General",q:"What is the name of the largest rainforest on Earth?",a:"amazon rainforest",alts:["the amazon","amazon"]},
  {id:"G192",cat:"General",q:"What is the capital of Spain?",a:"madrid"},
  {id:"G193",cat:"General",q:"In computing, what does 'CPU' stand for?",a:"central processing unit"},
  {id:"G194",cat:"General",q:"What is the name of the main character in 'Breaking Bad'?",a:"walter white",alts:["walt"]},
  {id:"G195",cat:"General",q:"What is the smallest planet in our solar system?",a:"mercury"},
  {id:"G196",cat:"General",q:"What is the name of the ice queen in Disney’s 'Frozen'?",a:"elsa"},
  {id:"G197",cat:"General",q:"What is the capital of Germany?",a:"berlin"},
  {id:"G198",cat:"General",q:"What is the name of the tallest building in the world (widely known)?",a:"burj khalifa",alts:["burj khalifa dubai"]},
  {id:"G199",cat:"General",q:"What is the name of the board game involving buying and trading properties?",a:"monopoly"},
  {id:"G200",cat:"General",q:"In RGB additive mixing, is yellow a primary color?",a:"no",alts:["nope","not in rgb","yellow is not a primary in rgb"]}
];
