// Trivia bank: 200 curated, non-random, human-knowable questions.
// Format: { id, cat, q, a, alts? } where `a` is primary answer, `alts` optional acceptable variants.
window.TRIVIA_BANK = [
  // Science (1–60)
  {id:"S001",cat:"Science",q:"What is the chemical symbol for gold?",a:"Au"},
  {id:"S002",cat:"Science",q:"What gas do plants absorb from the atmosphere for photosynthesis?",a:"carbon dioxide",alts:["co2"]},
  {id:"S003",cat:"Science",q:"What is the powerhouse of the cell?",a:"mitochondria",alts:["mitochondrion"]},
  {id:"S004",cat:"Science",q:"What is Earth's largest ocean?",a:"pacific ocean",alts:["pacific"]},
  {id:"S005",cat:"Science",q:"What particle has a negative electric charge?",a:"electron"},
  {id:"S006",cat:"Science",q:"What is the most abundant gas in Earth's atmosphere?",a:"nitrogen"},
  {id:"S007",cat:"Science",q:"What is the boiling point of water in Celsius at sea level?",a:"100",alts:["100°C","100 c"]},
  {id:"S008",cat:"Science",q:"What organ pumps blood through the body?",a:"heart"},
  {id:"S009",cat:"Science",q:"What is the chemical formula for water?",a:"h2o"},
  {id:"S010",cat:"Science",q:"What is the nearest star to Earth?",a:"the sun",alts:["sun"]},
  {id:"S011",cat:"Science",q:"What force keeps planets in orbit?",a:"gravity"},
  {id:"S012",cat:"Science",q:"What is the hardest natural substance?",a:"diamond"},
  {id:"S013",cat:"Science",q:"What is the unit of electrical resistance?",a:"ohm",alts:["Ω"]},
  {id:"S014",cat:"Science",q:"What is the pH of a neutral solution at 25°C?",a:"7"},
  {id:"S015",cat:"Science",q:"What blood type is known as the universal donor (red cells)?",a:"o negative",alts:["o-","o minus"]},
  {id:"S016",cat:"Science",q:"What vitamin is produced when skin is exposed to sunlight?",a:"vitamin d",alts:["d"]},
  {id:"S017",cat:"Science",q:"What is the largest planet in our solar system?",a:"jupiter"},
  {id:"S018",cat:"Science",q:"What gas is most associated with the greenhouse effect from fossil fuel burning?",a:"carbon dioxide",alts:["co2"]},
  {id:"S019",cat:"Science",q:"What is the main component of natural gas?",a:"methane"},
  {id:"S020",cat:"Science",q:"What do we call animals that eat both plants and meat?",a:"omnivores",alts:["omnivore"]},
  {id:"S021",cat:"Science",q:"What is the name of the process by which liquid water becomes vapor?",a:"evaporation"},
  {id:"S022",cat:"Science",q:"What is the largest organ in the human body?",a:"skin"},
  {id:"S023",cat:"Science",q:"What is the basic unit of life?",a:"cell"},
  {id:"S024",cat:"Science",q:"What do we call the study of weather?",a:"meteorology"},
  {id:"S025",cat:"Science",q:"What is the chemical symbol for sodium?",a:"na"},
  {id:"S026",cat:"Science",q:"What is the chemical symbol for iron?",a:"fe"},
  {id:"S027",cat:"Science",q:"What is the speed of light in vacuum (approx., km/s)?",a:"300000",alts:["299792","299792 km/s"]},
  {id:"S028",cat:"Science",q:"What part of the brain controls balance and coordination?",a:"cerebellum"},
  {id:"S029",cat:"Science",q:"What is the name of the galaxy that contains our solar system?",a:"milky way",alts:["milky way galaxy"]},
  {id:"S030",cat:"Science",q:"What is the common name for sodium chloride?",a:"salt",alts:["table salt"]},
  {id:"S031",cat:"Science",q:"What is the smallest unit of an element that retains its properties?",a:"atom"},
  {id:"S032",cat:"Science",q:"What is the planet known as the Red Planet?",a:"mars"},
  {id:"S033",cat:"Science",q:"What do you call a scientist who studies rocks and Earth's structure?",a:"geologist"},
  {id:"S034",cat:"Science",q:"What is the primary gas in the Sun?",a:"hydrogen"},
  {id:"S035",cat:"Science",q:"What is the name of the pigment that makes plants green?",a:"chlorophyll"},
  {id:"S036",cat:"Science",q:"What is the most common element in Earth's crust?",a:"oxygen"},
  {id:"S037",cat:"Science",q:"What is the name of the organ that filters blood and produces urine?",a:"kidney",alts:["kidneys"]},
  {id:"S038",cat:"Science",q:"What is the SI unit of force?",a:"newton",alts:["n"]},
  {id:"S039",cat:"Science",q:"What is the SI unit of energy?",a:"joule",alts:["j"]},
  {id:"S040",cat:"Science",q:"What do bees collect and use to make honey?",a:"nectar"},
  {id:"S041",cat:"Science",q:"What is the name for molten rock beneath Earth's surface?",a:"magma"},
  {id:"S042",cat:"Science",q:"What is the name for molten rock after it erupts onto the surface?",a:"lava"},
  {id:"S043",cat:"Science",q:"What is the primary function of red blood cells?",a:"carry oxygen",alts:["transport oxygen","carry oxygen to tissues"]},
  {id:"S044",cat:"Science",q:"What is the longest bone in the human body?",a:"femur"},
  {id:"S045",cat:"Science",q:"What is the name of the layer of gases surrounding Earth?",a:"atmosphere"},
  {id:"S046",cat:"Science",q:"What is the planet famous for its rings?",a:"saturn"},
  {id:"S047",cat:"Science",q:"What is the term for animals active at night?",a:"nocturnal"},
  {id:"S048",cat:"Science",q:"What do we call the process of a solid turning directly into a gas?",a:"sublimation"},
  {id:"S049",cat:"Science",q:"What is the name of the energy stored in chemical bonds?",a:"chemical energy"},
  {id:"S050",cat:"Science",q:"What is the study of heredity called?",a:"genetics"},
  {id:"S051",cat:"Science",q:"What are the tiny vessels where exchange of gases occurs in the lungs?",a:"alveoli",alts:["alveolus"]},
  {id:"S052",cat:"Science",q:"What is the name of Earth's natural satellite?",a:"moon",alts:["the moon"]},
  {id:"S053",cat:"Science",q:"What is the main organ of the nervous system?",a:"brain"},
  {id:"S054",cat:"Science",q:"What is the scientific name for humans?",a:"homo sapiens"},
  {id:"S055",cat:"Science",q:"What is the term for an animal that eats only plants?",a:"herbivore",alts:["herbivores"]},
  {id:"S056",cat:"Science",q:"What is the term for an animal that eats only meat?",a:"carnivore",alts:["carnivores"]},
  {id:"S057",cat:"Science",q:"What is the name of the instrument used to measure temperature?",a:"thermometer"},
  {id:"S058",cat:"Science",q:"Which planet is closest to the Sun?",a:"mercury"},
  {id:"S059",cat:"Science",q:"What is the term for a change in DNA sequence?",a:"mutation",alts:["a mutation"]},
  {id:"S060",cat:"Science",q:"What is the name of the process by which plants make food using sunlight?",a:"photosynthesis"},

  // Math (61–110)
  {id:"M061",cat:"Math",q:"What is 7 × 8?",a:"56"},
  {id:"M062",cat:"Math",q:"What is the square root of 81?",a:"9"},
  {id:"M063",cat:"Math",q:"What is π (pi) approximately to two decimal places?",a:"3.14"},
  {id:"M064",cat:"Math",q:"What is 15% of 200?",a:"30"},
  {id:"M065",cat:"Math",q:"What is 12²?",a:"144"},
  {id:"M066",cat:"Math",q:"What is the next prime after 7?",a:"11"},
  {id:"M067",cat:"Math",q:"What is the sum of angles in a triangle (degrees)?",a:"180"},
  {id:"M068",cat:"Math",q:"What is 2³?",a:"8"},
  {id:"M069",cat:"Math",q:"What is 9 × 9?",a:"81"},
  {id:"M070",cat:"Math",q:"What is the value of 0! (zero factorial)?",a:"1"},
  {id:"M071",cat:"Math",q:"What is 1/2 expressed as a decimal?",a:"0.5"},
  {id:"M072",cat:"Math",q:"How many sides does a hexagon have?",a:"6"},
  {id:"M073",cat:"Math",q:"What is 1000 divided by 25?",a:"40"},
  {id:"M074",cat:"Math",q:"What is the slope of a horizontal line?",a:"0"},
  {id:"M075",cat:"Math",q:"What is the area of a circle formula (in terms of r)?",a:"pi r^2",alts:["πr^2","π r^2"]},
  {id:"M076",cat:"Math",q:"What is 3/4 as a percentage?",a:"75%",alts:["75"]},
  {id:"M077",cat:"Math",q:"What is the derivative of x²?",a:"2x",alts:["2*x"]},
  {id:"M078",cat:"Math",q:"What is the value of 2 + 2 × 2?",a:"6"},
  {id:"M079",cat:"Math",q:"What is the median of 1, 3, 9?",a:"3"},
  {id:"M080",cat:"Math",q:"What is the circumference of a circle formula (in terms of r)?",a:"2pi r",alts:["2πr","2π r","2 pi r"]},
  {id:"M081",cat:"Math",q:"What is 10 choose 2 (C(10,2))?",a:"45"},
  {id:"M082",cat:"Math",q:"What is the sum of the first 10 positive integers?",a:"55"},
  {id:"M083",cat:"Math",q:"What is the value of |−7|?",a:"7"},
  {id:"M084",cat:"Math",q:"What is 0.25 as a fraction in simplest form?",a:"1/4"},
  {id:"M085",cat:"Math",q:"How many degrees are in a right angle?",a:"90"},
  {id:"M086",cat:"Math",q:"What is 3 × (4 + 5)?",a:"27"},
  {id:"M087",cat:"Math",q:"What is the next number in the sequence 2, 4, 8, 16, …?",a:"32"},
  {id:"M088",cat:"Math",q:"What is the prime factorization of 12?",a:"2^2 * 3",alts:["2^2×3","2*2*3","2×2×3"]},
  {id:"M089",cat:"Math",q:"What is the value of 5! (five factorial)?",a:"120"},
  {id:"M090",cat:"Math",q:"What is the sum of interior angles of a quadrilateral (degrees)?",a:"360"},
  {id:"M091",cat:"Math",q:"What is the sine of 90 degrees?",a:"1"},
  {id:"M092",cat:"Math",q:"What is the cosine of 0 degrees?",a:"1"},
  {id:"M093",cat:"Math",q:"What is 2/5 as a decimal?",a:"0.4"},
  {id:"M094",cat:"Math",q:"How many edges does a cube have?",a:"12"},
  {id:"M095",cat:"Math",q:"What is the value of 11 × 11?",a:"121"},
  {id:"M096",cat:"Math",q:"What is the square root of 144?",a:"12"},
  {id:"M097",cat:"Math",q:"What is the mean of 2, 4, 6, 8?",a:"5"},
  {id:"M098",cat:"Math",q:"What is 3⁴?",a:"81"},
  {id:"M099",cat:"Math",q:"What is the perimeter of a square with side length 7?",a:"28"},
  {id:"M100",cat:"Math",q:"What is the value of 1/8 as a decimal?",a:"0.125"},
  {id:"M101",cat:"Math",q:"How many faces does a cube have?",a:"6"},
  {id:"M102",cat:"Math",q:"What is the value of 20% of 150?",a:"30"},
  {id:"M103",cat:"Math",q:"What is 9 + 10?",a:"19"},
  {id:"M104",cat:"Math",q:"What is the product of the roots of x² − 5x + 6 = 0?",a:"6"},
  {id:"M105",cat:"Math",q:"What is the sum of the roots of x² − 5x + 6 = 0?",a:"5"},
  {id:"M106",cat:"Math",q:"What is the next prime after 29?",a:"31"},
  {id:"M107",cat:"Math",q:"What is log₁₀(1000)?",a:"3"},
  {id:"M108",cat:"Math",q:"What is the area of a rectangle with sides 8 and 5?",a:"40"},
  {id:"M109",cat:"Math",q:"What is 13 × 7?",a:"91"},
  {id:"M110",cat:"Math",q:"What is the sum of angles in a straight line (degrees)?",a:"180"},

  // Harry Potter (111–150)
  {id:"HP111",cat:"Harry Potter",q:"What is the name of Harry Potter’s owl?",a:"hedwig"},
  {id:"HP112",cat:"Harry Potter",q:"What platform number does the Hogwarts Express leave from?",a:"9 3/4",alts:["9¾","platform 9 3/4","9 and 3/4"]},
  {id:"HP113",cat:"Harry Potter",q:"What is the name of the Hogwarts headmaster in most of the series?",a:"albus dumbledore",alts:["dumbledore"]},
  {id:"HP114",cat:"Harry Potter",q:"What house is Harry Potter sorted into?",a:"gryffindor"},
  {id:"HP115",cat:"Harry Potter",q:"What is the name of the Hogwarts caretaker?",a:"argus filch",alts:["filch"]},
  {id:"HP116",cat:"Harry Potter",q:"What spell disarms an opponent?",a:"expelliarmus"},
  {id:"HP117",cat:"Harry Potter",q:"What is the spell to produce light from a wand?",a:"lumos"},
  {id:"HP118",cat:"Harry Potter",q:"What is the killing curse?",a:"avada kedavra"},
  {id:"HP119",cat:"Harry Potter",q:"What is Hermione’s last name?",a:"granger"},
  {id:"HP120",cat:"Harry Potter",q:"What is Ron’s last name?",a:"weasley"},
  {id:"HP121",cat:"Harry Potter",q:"What is the sport played on broomsticks called?",a:"quidditch"},
  {id:"HP122",cat:"Harry Potter",q:"What are the Hogwarts school colors of Ravenclaw typically?",a:"blue and bronze",alts:["blue & bronze","blue and silver"]},
  {id:"HP123",cat:"Harry Potter",q:"What is the name of the Dark Lord?",a:"voldemort",alts:["lord voldemort","tom riddle"]},
  {id:"HP124",cat:"Harry Potter",q:"Who is Harry’s godfather?",a:"sirius black",alts:["sirius"]},
  {id:"HP125",cat:"Harry Potter",q:"What is the name of Hagrid’s three-headed dog?",a:"fluffy"},
  {id:"HP126",cat:"Harry Potter",q:"What is the magical map that shows people in Hogwarts?",a:"marauder's map",alts:["marauders map","the marauder's map"]},
  {id:"HP127",cat:"Harry Potter",q:"What is the name of the school for witchcraft and wizardry?",a:"hogwarts",alts:["hogwarts school of witchcraft and wizardry"]},
  {id:"HP128",cat:"Harry Potter",q:"What creature guards the entrance to the Gryffindor common room?",a:"fat lady",alts:["the fat lady"]},
  {id:"HP129",cat:"Harry Potter",q:"What is the train that takes students to Hogwarts?",a:"hogwarts express"},
  {id:"HP130",cat:"Harry Potter",q:"What is the potion that brings luck called?",a:"felix felicis"},
  {id:"HP131",cat:"Harry Potter",q:"What is the spell to repel dementors?",a:"expecto patronum",alts:["patronus charm"]},
  {id:"HP132",cat:"Harry Potter",q:"What is the name of Harry’s mother?",a:"lily potter",alts:["lily"]},
  {id:"HP133",cat:"Harry Potter",q:"What is the name of Harry’s father?",a:"james potter",alts:["james"]},
  {id:"HP134",cat:"Harry Potter",q:"What is the name of the wizard prison?",a:"azkaban"},
  {id:"HP135",cat:"Harry Potter",q:"Who is the Half-Blood Prince?",a:"severus snape",alts:["snape"]},
  {id:"HP136",cat:"Harry Potter",q:"What is the ghost of Gryffindor called?",a:"nearly headless nick",alts:["sir nicholas de mimsy-porpington"]},
  {id:"HP137",cat:"Harry Potter",q:"What is the ghost of Ravenclaw called?",a:"grey lady",alts:["the grey lady","helena ravenclaw"]},
  {id:"HP138",cat:"Harry Potter",q:"What object is used to catch the Golden Snitch?",a:"seeker",alts:["the seeker"]},
  {id:"HP139",cat:"Harry Potter",q:"What is the name of the Weasleys’ home?",a:"the burrow",alts:["burrow"]},
  {id:"HP140",cat:"Harry Potter",q:"What is the name of the wizard bank?",a:"gringotts"},
  {id:"HP141",cat:"Harry Potter",q:"What is the spell used to unlock doors (basic)?",a:"alohomora"},
  {id:"HP142",cat:"Harry Potter",q:"What plant screams when pulled out of the ground?",a:"mandrake"},
  {id:"HP143",cat:"Harry Potter",q:"What is the name of the Hogwarts potions professor early on?",a:"severus snape",alts:["snape"]},
  {id:"HP144",cat:"Harry Potter",q:"What is the name of the gamekeeper at Hogwarts?",a:"rubeus hagrid",alts:["hagrid"]},
  {id:"HP145",cat:"Harry Potter",q:"What is the name of the cat belonging to Hermione?",a:"crookshanks"},
  {id:"HP146",cat:"Harry Potter",q:"What is the name of the house-elf who serves the Malfoys?",a:"dobby"},
  {id:"HP147",cat:"Harry Potter",q:"What is the name of the wizarding newspaper?",a:"daily prophet",alts:["the daily prophet"]},
  {id:"HP148",cat:"Harry Potter",q:"What is the name of the village near Hogwarts?",a:"hogsmeade"},
  {id:"HP149",cat:"Harry Potter",q:"What is the name of the invisible cloak Harry owns?",a:"invisibility cloak",alts:["cloak of invisibility"]},
  {id:"HP150",cat:"Harry Potter",q:"What is the password-protected magical barrier to Platform 9 3/4 located at?",a:"king's cross",alts:["kings cross","king’s cross"]},

  // General Knowledge / Pop Culture (151–200)
  {id:"G151",cat:"General",q:"What is the capital of France?",a:"paris"},
  {id:"G152",cat:"General",q:"Which planet is known for its Great Red Spot?",a:"jupiter"},
  {id:"G153",cat:"General",q:"Who wrote 'Romeo and Juliet'?",a:"william shakespeare",alts:["shakespeare"]},
  {id:"G154",cat:"General",q:"In which city is the Statue of Liberty located?",a:"new york",alts:["new york city","nyc"]},
  {id:"G155",cat:"General",q:"What is the largest mammal?",a:"blue whale"},
  {id:"G156",cat:"General",q:"What is the currency of Japan?",a:"yen"},
  {id:"G157",cat:"General",q:"What is the capital of Italy?",a:"rome"},
  {id:"G158",cat:"General",q:"Which continent is the Sahara Desert on?",a:"africa"},
  {id:"G159",cat:"General",q:"What is the tallest mountain in the world (above sea level)?",a:"mount everest",alts:["everest"]},
  {id:"G160",cat:"General",q:"What is the longest river in the world (commonly cited)?",a:"nile",alts:["the nile"]},
  {id:"G161",cat:"General",q:"What is the name of the painting with a woman smiling by Leonardo da Vinci?",a:"mona lisa"},
  {id:"G162",cat:"General",q:"Which musical instrument has 88 keys (standard)?",a:"piano"},
  {id:"G163",cat:"General",q:"What is the largest continent by area?",a:"asia"},
  {id:"G164",cat:"General",q:"What is the smallest prime number?",a:"2"},
  {id:"G165",cat:"General",q:"What is the chemical symbol for oxygen?",a:"o"},
  {id:"G166",cat:"General",q:"Which country gifted the Statue of Liberty to the United States?",a:"france"},
  {id:"G167",cat:"General",q:"What is the name of the fictional city where Batman operates?",a:"gotham",alts:["gotham city"]},
  {id:"G168",cat:"General",q:"What is the name of the Greek god of the sea?",a:"poseidon"},
  {id:"G169",cat:"General",q:"What is the largest planet in our solar system?",a:"jupiter"},
  {id:"G170",cat:"General",q:"What is the primary language spoken in Brazil?",a:"portuguese"},
  {id:"G171",cat:"General",q:"What is the term for a word that is the same forwards and backwards?",a:"palindrome"},
  {id:"G172",cat:"General",q:"What is the name of the ship on which the Pilgrims traveled to America in 1620?",a:"mayflower"},
  {id:"G173",cat:"General",q:"Which ocean is off the California coast?",a:"pacific ocean",alts:["pacific"]},
  {id:"G174",cat:"General",q:"What is the largest internal organ in the human body?",a:"liver"},
  {id:"G175",cat:"General",q:"How many players are on a soccer team on the field (per side)?",a:"11"},
  {id:"G176",cat:"General",q:"What is the main character’s name in 'The Legend of Zelda' series?",a:"link"},
  {id:"G177",cat:"General",q:"What is the capital of Canada?",a:"ottawa"},
  {id:"G178",cat:"General",q:"What instrument measures atmospheric pressure?",a:"barometer"},
  {id:"G179",cat:"General",q:"Who painted the ceiling of the Sistine Chapel (commonly credited)?",a:"michelangelo"},
  {id:"G180",cat:"General",q:"What is the name of the fictional wizard in 'The Lord of the Rings' who leads the Fellowship?",a:"gandalf"},
  {id:"G181",cat:"General",q:"What is the largest country by area?",a:"russia"},
  {id:"G182",cat:"General",q:"What is the name of the longest-running animated TV series in the US?",a:"the simpsons",alts:["simpsons"]},
  {id:"G183",cat:"General",q:"What is the capital of Australia?",a:"canberra"},
  {id:"G184",cat:"General",q:"Which element has the atomic number 1?",a:"hydrogen"},
  {id:"G185",cat:"General",q:"What is the name of the famous clock tower in London (nickname)?",a:"big ben"},
  {id:"G186",cat:"General",q:"What is the largest bone in the human body?",a:"femur"},
  {id:"G187",cat:"General",q:"Which planet is famous for its rings?",a:"saturn"},
  {id:"G188",cat:"General",q:"What is the main ingredient in guacamole?",a:"avocado",alts:["avocados"]},
  {id:"G189",cat:"General",q:"What is the name of Sherlock Holmes’s friend and assistant?",a:"dr watson",alts:["watson","john watson","dr. watson"]},
  {id:"G190",cat:"General",q:"What is the term for an angle greater than 90 degrees but less than 180 degrees?",a:"obtuse"},
  {id:"G191",cat:"General",q:"What is the name of the largest rainforest on Earth?",a:"amazon rainforest",alts:["the amazon","amazon"]},
  {id:"G192",cat:"General",q:"What is the capital of Spain?",a:"madrid"},
  {id:"G193",cat:"General",q:"In computing, what does 'CPU' stand for?",a:"central processing unit"},
  {id:"G194",cat:"General",q:"What is the name of the main character in 'Breaking Bad'?",a:"walter white",alts:["walt"]},
  {id:"G195",cat:"General",q:"What is the smallest planet in our solar system?",a:"mercury"},
  {id:"G196",cat:"General",q:"What is the name of the ice queen in Disney’s 'Frozen'?",a:"elsa"},
  {id:"G197",cat:"General",q:"What is the capital of Germany?",a:"berlin"},
  {id:"G198",cat:"General",q:"What is the name of the tallest building in the world (widely known)?",a:"burj khalifa",alts:["burj khalifa dubai"]},
  {id:"G199",cat:"General",q:"What is the name of the board game involving buying and trading properties?",a:"monopoly"},
  {id:"G200",cat:"General",q:"What is the primary color of the 'yellow' in RGB additive mixing?",a:"there is no yellow",alts:["no yellow","yellow is not a primary in rgb"]}
];
